// Code generated by release.yml for v0.5.1. DO NOT EDIT.

package tepin

// libVersion is the GitHub release tag (without the leading v) whose
// libtepin assets this driver downloads.
const libVersion = "0.5.1"

// libSHA256 pins each platform asset, keyed by "<os>-<arch>" as named
// on the release: libtepin-<key>.<dylib|so|dll>.
var libSHA256 = map[string]string{
	"darwin-arm64": "cd1531ef4aa1eb8fa9af9bc2178a63cb347ca6603c4d8c1d69787481606864e7",
	"linux-x64":    "4fa571e521c3d123c6b815fbee46fb80cb3610137ab30d1ea0a31a106c2ce9d6",
	"win32-x64":    "d2982f3e92db57539f365f8e40a419a265d6990c6f644d4596a6f2cc91b58506",
}
