// Code generated by release.yml for v0.5.0. DO NOT EDIT.

package tepin

// libVersion is the GitHub release tag (without the leading v) whose
// libtepin assets this driver downloads.
const libVersion = "0.5.0"

// libSHA256 pins each platform asset, keyed by "<os>-<arch>" as named
// on the release: libtepin-<key>.<dylib|so|dll>.
var libSHA256 = map[string]string{
	"darwin-arm64": "65eb6b1e1c29c1f708dca6f1dc16029f3427457d286d1ceff9550bc0d2b3ee27",
	"linux-x64":    "50726fffac22d084ad539fb5df3be1fcec54d095f141406791c17a21fb5c161c",
	"win32-x64":    "cb7d36bbdbfa52e06169948208b061341dfca3e927abc777ec9e882ab20ae1fa",
}
