//! The .tepin container format.
//!
//! A .tepin file is a 4 KiB human/LLM-readable preamble followed by a redb
//! database payload at a fixed offset. The preamble is static (write-once):
//! live schema information lives in the meta table inside the payload, where
//! `tepin inspect` reads it. Anyone — or any LLM — running `head` on the file
//! learns exactly what it is and how to work with it.

use std::fs::File;
use std::io;

use serde::{Deserialize, Serialize};

use crate::error::{Result, TepinError};

/// Size of the preamble; the redb payload starts at exactly this offset.
pub const PREAMBLE_LEN: u64 = 4096;
/// Current container format version. Pre-1.0 this may change freely;
/// `tepin migrate` always covers every version Engram has ever used.
pub const FORMAT_VERSION: u32 = 0;

const MAGIC: &[u8] = b"tepindb";
const META_START: &str = "==== TEPIN MACHINE METADATA (JSON) ====";
const META_END: &str = "==== END ====";

/// The machine-parsable block embedded in the preamble.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreambleMeta {
    pub magic: String,
    pub format_version: u32,
    pub payload_offset: u64,
    pub created_with: String,
}

/// Render the full 4 KiB preamble. The text is the LLM's landing page —
/// we use all the room we have.
pub fn build_preamble() -> Vec<u8> {
    let meta = PreambleMeta {
        magic: "tepindb".to_string(),
        format_version: FORMAT_VERSION,
        payload_offset: PREAMBLE_LEN,
        created_with: format!("tepin-core {}", env!("CARGO_PKG_VERSION")),
    };
    let meta_json = serde_json::to_string(&meta).expect("preamble meta serializes");

    let text = format!(
        r#"tepindb v{FORMAT_VERSION} — AI-first single-file database
=========================================================

WHAT THIS FILE IS
This is a TepinDB database: JSON documents in named collections, with
built-in vector search. The binary payload starts at byte {PREAMBLE_LEN}.
Do not edit this file by hand — use the tools below.

HOW TO WORK WITH IT (humans and AI agents alike)
  npx tepindb inspect <this-file>
      Markdown report: collections, their purposes, schemas, stats.
      Start here — it tells you everything this database contains.
  npx tepindb query  <this-file> <collection> '{{"field": "value"}}'
      MongoDB-style JSON filters. Answers in JSON.
  npx tepindb search <this-file> "any natural language query"
      Semantic vector search across embedded collections.
  npx tepindb insert <this-file> <collection> '{{"any": "json"}}'
  npx tepindb update <this-file> <collection> <id> '{{"any": "json"}}'
  npx tepindb delete <this-file> <collection> <id>
  npx tepindb mcp    <this-file>
      Serve MCP tools over stdio — plug this database into an AI agent.

CONVENTIONS
  Documents carry a short sortable string id in "_id".
  Every command prints JSON (inspect prints markdown).
  Every error is {{"error": {{"code", "message", "hint"}}}} — the hint
  says what to do next. Set TEPIN_DB=<this-file> to omit the path.

MORE
  Rust API: the tepin-core crate. Everything about this database lives
  inside this one file — there is no external config.
  Source, docs, security policy: https://github.com/tepindb/tepindb

{META_START}
{meta_json}
{META_END}
"#
    );

    let mut buf = text.into_bytes();
    assert!(
        buf.len() <= PREAMBLE_LEN as usize,
        "preamble text exceeds {PREAMBLE_LEN} bytes"
    );
    buf.resize(PREAMBLE_LEN as usize, b'\n');
    buf
}

/// Parse and validate a preamble read from an untrusted file.
///
/// This is attacker-controlled input (an agent may download a .tepin file
/// from anywhere) — it is fuzzed and must never panic.
pub fn parse_preamble(bytes: &[u8]) -> Result<PreambleMeta> {
    if bytes.len() < MAGIC.len() || !bytes.starts_with(MAGIC) {
        return Err(TepinError::new(
            "not_a_tepin_file",
            "this file does not start with the tepindb magic",
            "check that the path points to a .tepin database; create one with `tepin insert`",
        ));
    }
    if bytes.len() < PREAMBLE_LEN as usize {
        return Err(TepinError::new(
            "invalid_preamble",
            format!(
                "file is only {} bytes; a .tepin file is at least {PREAMBLE_LEN}",
                bytes.len()
            ),
            "the file is truncated or corrupt; restore it from a backup",
        ));
    }
    let head = String::from_utf8_lossy(&bytes[..PREAMBLE_LEN as usize]);
    let meta_json = head
        .split_once(META_START)
        .and_then(|(_, rest)| rest.split_once(META_END))
        .map(|(json, _)| json.trim())
        .ok_or_else(|| {
            TepinError::new(
                "invalid_preamble",
                "preamble is missing its machine metadata block",
                "the file is corrupt or from an incompatible version; run `tepin migrate`",
            )
        })?;
    let meta: PreambleMeta = serde_json::from_str(meta_json).map_err(|e| {
        TepinError::new(
            "invalid_preamble",
            format!("machine metadata block is not valid JSON: {e}"),
            "the file is corrupt or from an incompatible version; run `tepin migrate`",
        )
    })?;
    if meta.magic != "tepindb" {
        return Err(TepinError::new(
            "invalid_preamble",
            format!("unexpected magic {:?} in metadata block", meta.magic),
            "the file is corrupt; restore it from a backup",
        ));
    }
    if meta.format_version > FORMAT_VERSION {
        return Err(TepinError::new(
            "format_too_new",
            format!(
                "file has format v{}, this build reads up to v{FORMAT_VERSION}",
                meta.format_version
            ),
            "upgrade tepindb (`npm i -g tepindb` / `cargo install tepin-cli`) and retry",
        ));
    }
    if meta.payload_offset != PREAMBLE_LEN {
        return Err(TepinError::new(
            "invalid_preamble",
            format!("unsupported payload offset {}", meta.payload_offset),
            "the file is corrupt or from an incompatible version; run `tepin migrate`",
        ));
    }
    Ok(meta)
}

/// A redb storage backend that hides the preamble: redb sees a file that
/// starts at byte 0, we store its bytes starting at `PREAMBLE_LEN`.
#[derive(Debug)]
pub struct PreambleBackend {
    file: File,
}

impl PreambleBackend {
    pub fn new(file: File) -> Self {
        Self { file }
    }
}

#[cfg(unix)]
fn read_at(file: &File, buf: &mut [u8], offset: u64) -> io::Result<()> {
    use std::os::unix::fs::FileExt;
    file.read_exact_at(buf, offset)
}

#[cfg(unix)]
fn write_at(file: &File, buf: &[u8], offset: u64) -> io::Result<()> {
    use std::os::unix::fs::FileExt;
    file.write_all_at(buf, offset)
}

#[cfg(windows)]
fn read_at(file: &File, mut buf: &mut [u8], mut offset: u64) -> io::Result<()> {
    use std::os::windows::fs::FileExt;
    while !buf.is_empty() {
        match file.seek_read(buf, offset) {
            Ok(0) => return Err(io::ErrorKind::UnexpectedEof.into()),
            Ok(n) => {
                buf = &mut buf[n..];
                offset += n as u64;
            }
            Err(e) if e.kind() == io::ErrorKind::Interrupted => {}
            Err(e) => return Err(e),
        }
    }
    Ok(())
}

#[cfg(windows)]
fn write_at(file: &File, mut buf: &[u8], mut offset: u64) -> io::Result<()> {
    use std::os::windows::fs::FileExt;
    while !buf.is_empty() {
        match file.seek_write(buf, offset) {
            Ok(0) => return Err(io::ErrorKind::WriteZero.into()),
            Ok(n) => {
                buf = &buf[n..];
                offset += n as u64;
            }
            Err(e) if e.kind() == io::ErrorKind::Interrupted => {}
            Err(e) => return Err(e),
        }
    }
    Ok(())
}

impl redb::StorageBackend for PreambleBackend {
    fn len(&self) -> io::Result<u64> {
        Ok(self.file.metadata()?.len().saturating_sub(PREAMBLE_LEN))
    }

    fn read(&self, offset: u64, out: &mut [u8]) -> io::Result<()> {
        read_at(&self.file, out, offset + PREAMBLE_LEN)
    }

    fn set_len(&self, len: u64) -> io::Result<()> {
        self.file.set_len(len + PREAMBLE_LEN)
    }

    fn sync_data(&self) -> io::Result<()> {
        self.file.sync_data()
    }

    fn write(&self, offset: u64, data: &[u8]) -> io::Result<()> {
        write_at(&self.file, data, offset + PREAMBLE_LEN)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preamble_is_exactly_4k_and_round_trips() {
        let bytes = build_preamble();
        assert_eq!(bytes.len(), PREAMBLE_LEN as usize);
        let meta = parse_preamble(&bytes).unwrap();
        assert_eq!(meta.format_version, FORMAT_VERSION);
        assert_eq!(meta.payload_offset, PREAMBLE_LEN);
    }

    #[test]
    fn preamble_is_readable_text() {
        let bytes = build_preamble();
        let text = std::str::from_utf8(&bytes).unwrap();
        assert!(text.starts_with("tepindb"));
        assert!(text.contains("npx tepindb inspect"));
    }

    #[test]
    fn garbage_is_rejected_politely() {
        for bad in [
            &b""[..],
            &b"sqlite format 3"[..],
            &[0u8; 8192][..],
            &b"tepindb but truncated"[..],
        ] {
            let err = parse_preamble(bad).unwrap_err();
            assert!(!err.code.is_empty());
            assert!(!err.hint.is_empty());
        }
    }
}
